# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(551, 601)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 531, 359))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 5, 0, 1, 5)
        self.statusProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.statusProgressBar.setProperty("value", 0)
        self.statusProgressBar.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.statusProgressBar.setTextVisible(True)
        self.statusProgressBar.setOrientation(QtCore.Qt.Horizontal)
        self.statusProgressBar.setInvertedAppearance(False)
        self.statusProgressBar.setFormat("")
        self.statusProgressBar.setObjectName("statusProgressBar")
        self.gridLayout_2.addWidget(self.statusProgressBar, 7, 0, 1, 5)
        self.numberArticlesLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numberArticlesLabel.sizePolicy().hasHeightForWidth())
        self.numberArticlesLabel.setSizePolicy(sizePolicy)
        self.numberArticlesLabel.setObjectName("numberArticlesLabel")
        self.gridLayout_2.addWidget(self.numberArticlesLabel, 6, 1, 1, 1)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout_3.setObjectName("formLayout_3")
        self.cancelAnalyzeButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelAnalyzeButton.setObjectName("cancelAnalyzeButton")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.cancelAnalyzeButton)
        self.startAnalyzeButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startAnalyzeButton.sizePolicy().hasHeightForWidth())
        self.startAnalyzeButton.setSizePolicy(sizePolicy)
        self.startAnalyzeButton.setMinimumSize(QtCore.QSize(30, 0))
        self.startAnalyzeButton.setBaseSize(QtCore.QSize(30, 0))
        self.startAnalyzeButton.setCheckable(True)
        self.startAnalyzeButton.setChecked(False)
        self.startAnalyzeButton.setObjectName("startAnalyzeButton")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.startAnalyzeButton)
        self.gridLayout_2.addLayout(self.formLayout_3, 8, 4, 1, 1)
        self.numberArticlesLabelInfo = QtWidgets.QLabel(self.centralwidget)
        self.numberArticlesLabelInfo.setObjectName("numberArticlesLabelInfo")
        self.gridLayout_2.addWidget(self.numberArticlesLabelInfo, 6, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.addArticle = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addArticle.sizePolicy().hasHeightForWidth())
        self.addArticle.setSizePolicy(sizePolicy)
        self.addArticle.setObjectName("addArticle")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.addArticle)
        self.spinArticleBox = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinArticleBox.sizePolicy().hasHeightForWidth())
        self.spinArticleBox.setSizePolicy(sizePolicy)
        self.spinArticleBox.setBaseSize(QtCore.QSize(0, 0))
        self.spinArticleBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinArticleBox.setObjectName("spinArticleBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinArticleBox)
        self.gridLayout_2.addLayout(self.formLayout, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_2.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout_2.setContentsMargins(0, 0, 5, -1)
        self.formLayout_2.setHorizontalSpacing(5)
        self.formLayout_2.setObjectName("formLayout_2")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setMaximum(99)
        self.spinBox.setObjectName("spinBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.removeArticle = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeArticle.sizePolicy().hasHeightForWidth())
        self.removeArticle.setSizePolicy(sizePolicy)
        self.removeArticle.setCheckable(False)
        self.removeArticle.setAutoRepeat(False)
        self.removeArticle.setObjectName("removeArticle")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.removeArticle)
        self.gridLayout_2.addLayout(self.formLayout_2, 4, 4, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditOpenFile = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditOpenFile.sizePolicy().hasHeightForWidth())
        self.lineEditOpenFile.setSizePolicy(sizePolicy)
        self.lineEditOpenFile.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditOpenFile.setBaseSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditOpenFile.setFont(font)
        self.lineEditOpenFile.setObjectName("lineEditOpenFile")
        self.horizontalLayout.addWidget(self.lineEditOpenFile)
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setMinimumSize(QtCore.QSize(30, 0))
        self.toolButton.setCheckable(False)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 3, 0, 1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 551, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.numberArticlesLabel.setText(_translate("MainWindow", "0"))
        self.cancelAnalyzeButton.setText(_translate("MainWindow", "Отмена"))
        self.startAnalyzeButton.setText(_translate("MainWindow", "Анализ"))
        self.numberArticlesLabelInfo.setText(_translate("MainWindow", "Количество статей :"))
        self.addArticle.setText(_translate("MainWindow", "Добавить "))
        self.label.setText(_translate("MainWindow", "Папка назначения"))
        self.removeArticle.setText(_translate("MainWindow", "Удалить"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.menu.setTitle(_translate("MainWindow", "Файл"))


